Traderdock/Traderdock.Web/Areas/Admin/Controllers/TTSettingsController.cs
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Traderdock.Entity.Model;
using Traderdock.Model.TTModel;
using Traderdock.Services;
using Traderdock.Web.Areas.Admin.Authorization;

namespace Traderdock.Web.Areas.Admin.Controllers
{
    [Authorization]
    public class TTSettingsController : Controller
    {
        #region Global Variables
        TTSettingsService objSettingService;
        #endregion

        #region Get Setting
        /// <summary>
        /// Index Get
        /// </summary>
        /// <returns></returns>
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Index()
        {
            List<SettingModel> lstSettingModel = new List<SettingModel>();
            return View(lstSettingModel);
        }

        /// <summary>
        /// Settings_Read
        /// </summary>
        /// <param name="model"></param>
        /// <param name="SearchFirstName"></param>
        /// <param name="statusFilter"></param>
        /// <returns></returns>
        public JsonResult Settings_Read(DataSourceRequest model, string SearchFirstName = "", string statusFilter = "")
        {
            objSettingService = new TTSettingsService();
            var users = objSettingService.SettingsList(SearchFirstName, model.Page - 1, ((Convert.ToInt32(model.PageSize) > 0) ? model.PageSize : 10), statusFilter);
            var gridModel = new DataSourceResult
            {
                Data = users,
                Total = users.TotalCount
            };
            return Json(gridModel);
        }

        #endregion

        #region Add Edit Setting.
        /// <summary>
        /// Edit Setting
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult AddEditSetting(Int64? id)
        {
            objSettingService = new TTSettingsService();
            SettingModel objSettingModel = new SettingModel();
            if (id > 0)
            {
                objSettingModel = objSettingService.GetSetting(id);
            }
            return View(objSettingModel);
        }

        /// <summary>
        /// Add Edit Settings
        /// </summary>
        /// <param name="objModel"></param>
        /// <param name="file1"></param>
        /// <returns></returns>
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult AddEditSettings(SettingModel objSettingModel)
        {
            objSettingService = new TTSettingsService();
            if (ModelState.IsValid)
            {
                if (objSettingModel.setting_id > 0)
                {
                    objSettingModel.modified_on = System.DateTime.UtcNow;
                    objSettingModel.modified_by = Convert.ToInt32(Session["UserID"]);
                    bool bFlag = objSettingService.AddEditSettings(objSettingModel);
                    if (bFlag)
                    {
                        if (objSettingModel.setting_name == "PageSize")
                        {
                            Session["PageSize"] = objSettingModel.setting_value;
                        }
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    bool bFlag = objSettingService.AddEditSettings(objSettingModel);
                    return RedirectToAction("Index");
                }
            }
            return View(objSettingModel);
        }
        #endregion
    }
}

Traderdock/Traderdock.Web/Areas/Admin/Views/TTSettings/AddEditSetting.cshtml
@model Traderdock.Entity.Model.SettingModel

@{
    ViewBag.Title = "Edit FAQ Master";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    string StrPath = System.Web.Configuration.WebConfigurationManager.AppSettings["SitePath"];
    ViewBag.SubMenu = "settings";
}


<link href="~/Content/dist/css/custom.css" rel="stylesheet" />
<link href="~/Content/plugins/Kendo/kendo.common.min.css" rel="stylesheet" />
<link href="~/Content/plugins/Kendo/kendo.metro.min.css" rel="stylesheet" />
<script src="~/Content/plugins/Kendo/kendo.web.min.js"></script>

<section class="content-header">
    <h1>
        Settings
    </h1>
    <ol class="breadcrumb">
        <li><a href="~/admin/dashboard/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Settings</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div>
        <!-- Horizontal Form -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"> Settings</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->

            @using (Html.BeginForm("AddEditSettings", "Settings", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form" }))
            {
                <div class="box-body">
                    <h6 style="color:red;display:none;" id="errormsg"> </h6>
                    <div class="row">
                        <div class="col-md-10">
                            <div class="row">
                                <div class="col-sm-6">
                                    @Html.HiddenFor(m=>m.setting_id)
                                    @Html.HiddenFor(m=>m.setting_name)
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.default_label)
                                        @Html.TextBoxFor(model => model.default_label, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.default_label, "", new { @style = "color:red" })
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.setting_value)
                                        @Html.TextAreaFor(m => m.setting_value, new { @class = "form-control", @placeholder = "" })
                                        @Html.ValidationMessageFor(model => model.setting_value, "", new { @style = "color:red" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                    <div class="box-footer">
                        <div class="row">
                            <div class="col-md-8 col-lg-6">
                                <div class="row">
                                    <div class="col-sm-8">
                                        <button type="submit" id="btnSave" class="btn btn-primary load-button ">Submit</button>
                                        <button type="button" class="btn btn-default" onclick="fnCancel();">Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-footer -->
            }
            @Html.Hidden("Message", @TempData["Msg"])
        </div>
    </div>
    <div id="success-alert" class="toast-top-right" style="position:absolute;top:80px;right:0; height:100px;display:block; width:270px;" aria-live="polite" role="alert">
        <div class="toast toast-success">
            <button class="toast-close-button" role="button">×</button>
            <div class="toast-title"></div>
            <div class="toast-message">
                <p class="text"></p>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    $("document").ready(function () {
        if ($("#Message").val() != '') {
            toastr.success($("#Message").val());
        }
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal-blue',
            radioClass: 'iradio_minimal-blue'
        });
    });

    function fnCancel() {
        window.location.href = '@Url.Action("index", "settings")';
    }
</script>

Traderdock/Traderdock.Web/Areas/Admin/Views/TTSettings/Index.cshtml
@model List<Traderdock.Entity.Model.SettingModel>
@{
    ViewBag.Title = "Settings List";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    string StrPath = System.Web.Configuration.WebConfigurationManager.AppSettings["SiteLink"];
    string PageSize = Session["PageSize"].ToString();
    ViewBag.SubMenu = "settings";
}
<link href="~/Content/dist/css/custom.css" rel="stylesheet" />
<link href="~/Content/plugins/Kendo/kendo.common.min.css" rel="stylesheet" />
<link href="~/Content/plugins/Kendo/kendo.metro.min.css" rel="stylesheet" />
<script src="~/Content/plugins/Kendo/kendo.web.min.js"></script>
<section class="content-header">
    <h1>
        Settings
    </h1>
    <ol class="breadcrumb">
        <li><a href="~/admin/dashboard/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Settings</li>
    </ol>
</section>
<section class="content">
    <div>
        <div>
            <section>
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h2 class="box-title">Settings List</h2>
                        @*<div class="box-tools">
                            <a href="~/admin/settings/addeditsettings" class="addlink btn btn-primary pull-right margin-r-5">
                                <i class="btn-icon fa fa-plus"></i> Add New Settings
                            </a>
                        </div>*@
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <form>
                            <div id="grid" class="display table table-bordered table-striped k-content">
                            </div>
                            @Html.Hidden("statusFilter")
                            @Html.Hidden("checkedData")
                        </form>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </section>
        </div>
    </div>
    <div id="modalConfirmYesNo" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button"
                            class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 id="lblTitleConfirmYesNo" class="modal-title">Confirmation</h4>
                </div>
                <div class="modal-body">
                    <p id="lblMsgConfirmYesNo"></p>
                </div>
                <div class="modal-footer">
                    <button id="btnYesConfirmYesNo"
                            type="button" class="btn btn-primary">
                        Yes
                    </button>
                    <button id="btnNoConfirmYesNo"
                            type="button" class="btn btn-default">
                        No
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div id="SelectAlert">
    </div>
    @Html.Hidden("mm", @TempData["Msg"])
</section>
<script type="text/javascript">
    var pageLimit = '@PageSize';
    function OnFilter(values) {
        $("#statusFilter").val(values);
        $("#grid").data("kendoGrid").dataSource.read();
    }
    $(document).ready(function () {
        var modelData = @Html.Raw(Json.Encode(Model))
            $('#grid').kendoGrid({
                scrollable: true,
                sortable: true,
                pageable: true,
                filterable: false,
                dataSource: {
                    type: "json",
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("Settings_Read", "TTSettings"))",
                            type: "POST",
                            dataType: "json"
                        },
                        update: {
                            url: "@Html.Raw(Url.Action("AddEditSettings", "TTSettings"))",
                            dataType: "json"
                        },
                        parameterMap: function (options, operation) {
                            if (operation !== "read" && options.models) {
                                return { models: kendo.stringify(options.models) };
                            }
                        }
                    },
                    schema: {
                        data: "Data",
                        total: "Total"
                    },
                    pageSize: @PageSize,
                    serverPaging: true,
                    serverFiltering: true,
                    //Filterable:true,
                },
                columns: [
                    { field: "default_label", filterable:false,editable:false, title: "Setting Name", format: "{0:c}"},
                    { field: "setting_value", validation: { required: true }, title:"Setting Value"},
                    { command: ["edit"], title: "Actions"}],
                editable: "inline"
            });

        $('#btnSearch').on("click", function (e) {
            var grid = $('#grid').data('kendoGrid');
            grid.dataSource.page(1); //new search. Set page size to 1
            return false;
        });
        function additionalData() {
            var data = {
                SearchFirstName: $('#category').val(),
                statusFilter: $('#statusFilter').val()
            };
            return data;
        }
        // $("#success-alert").hide();
        if ($('#mm').val().length != 0) {
            toastr.success($('#mm').val());
        }
    });
</script>
<script type="text/javascript">
    var pageLimit = '@PageSize';
    function AsyncConfirmYesNo(title, msg, yesFn, noFn, id) {
        var $confirm = $("#modalConfirmYesNo");
        $confirm.modal('show');
        $("#lblTitleConfirmYesNo").html(title);
        $("#lblMsgConfirmYesNo").html(msg);
        $("#btnYesConfirmYesNo").off('click').click(function () {
            $.ajax({
                type: "GET",
                url: '@Url.Action("Delete", "faqcategory", new { area = "admin" })',
                data: {
                    ID: id
                },
                success: function (result) {
                    if (result.success == true) {
                        $confirm.modal("hide");
                        $("#grid").data("kendoGrid").dataSource.read();
                    }
                    else {
                        $confirm.modal("hide");
                        $("#grid").data("kendoGrid").dataSource.read();
                    }
                },
                error: function (result) {
                    alert('error');
                }
            });
        });
        $("#btnNoConfirmYesNo").off('click').click(function () {

            $confirm.modal("hide");
        });
    }

    function MyYesFunction(id) {
        return id;
    }

    function MyNoFunction(id) {
        return id;
    }

    //For Delete
    function RemoveSelectedRow(id) {
        AsyncConfirmYesNo(
       "Delete confirmation.",
       "Are you sure want to delete ?",
       MyYesFunction(),
       MyNoFunction(),
       id
         );
    }


    function refreshGrid() {

        $.ajax({
            type: "Post",
            url: '@StrPath/admin/Settings/Settings_Read/',
            data: {
                filter: $('#category').val()
            },
            success: function (result) {
                alert('succsess');
                $("#grid").data("kendoGrid").dataSource.read();
            },
            error: function (result) {
                alert('error');
            }
        });
        grid.dataSource.filter($filter);
        grid.dataSource.read();
    }
    function OnFilter(values) {
        $("#statusFilter").val(values);
        $("#grid").data("kendoGrid").dataSource.read();
    }
</script>